version: '3' # docker-compose version
# Definimos servicios y contenedores
services:
  frontend: #Frontend Angular
    build: Frontend # Dockerfile
    ports:
      - "4200:4200" # port 
    container_name: frontend
    restart: always
  backend: #Backend Node
    build: Backend # Dockerfile
    ports:
      - "3000:3000" # ports 
    container_name: backend
    restart: always
    links:
      - database # link this service to the database service
  database: # DB mysql
    build: Database # Dockerfile
    container_name: database
    restart: always